AWSTemplateFormatVersion: '2010-09-09'
Description: Builds vpc and supporting infra.
Parameters:
  ServiceName:
    Type: String
    Default: mcm-quest-service
  GitHubToken:
    Description: 'Personal Access Token for authenticating to GitHub'
    Type: 'String'
    NoEcho: true

Resources:
  Vpc:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: "./Vpc.yml"

  Roles:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: "./Roles.yml"
      Parameters:
        CodePipelineS3Bucket: !GetAtt Bucket.Outputs.Bucket

  Kms:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: "./Kms.yml"

  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: "./SecurityGroups.yml"
      Parameters:
        VpcId: !GetAtt Vpc.Outputs.VpcId

  Bucket:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: "./S3.yml"
      Parameters:
        PipelineKey: !GetAtt Kms.Outputs.PipelineKey
        ServiceName: !Ref ServiceName

  Ecs:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: "./Ecs.yml"
      Parameters:
        ServiceName: !Sub ${ServiceName}

  Alb:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: "./Alb.yml"
      Parameters:
        PublicSubnet1: !GetAtt Vpc.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt Vpc.Outputs.PublicSubnet2
        VpcId: !GetAtt Vpc.Outputs.VpcId
        AlbSecurityGroup: !GetAtt SecurityGroups.Outputs.AlbSecurityGroup

  Pipeline:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: "./Pipeline.yml"
      Parameters:
        VpcId: !GetAtt Vpc.Outputs.VpcId
        PrivateSubnetA: !GetAtt Vpc.Outputs.PrivateSubnetA
        PrivateSubnetB: !GetAtt Vpc.Outputs.PrivateSubnetB
        ExecutionRoleArn: !GetAtt Roles.Outputs.ExecutionRoleArn
        TaskRoleArn: !GetAtt Roles.Outputs.TaskRoleArn
        AutoScalingRoleArn: !GetAtt Roles.Outputs.AutoScalingRoleArn
        AlbSecurityGroup: !GetAtt SecurityGroups.Outputs.AlbSecurityGroup
        ClusterName: !GetAtt Ecs.Outputs.ClusterName
        ServiceName: !Ref ServiceName
        ECSSecurityGroup: !GetAtt SecurityGroups.Outputs.ECSSecurityGroup
        GitHubToken: !Ref GitHubToken
        CodeBuildSecurityGroup: !GetAtt SecurityGroups.Outputs.CodeBuildSecurityGroup
        CodePipelineRoleArn: !GetAtt Roles.Outputs.CodePipelineRoleArn
        CodeBuildRoleArn: !GetAtt Roles.Outputs.CodeBuildRoleArn
        CodePipelineBucket: !GetAtt Bucket.Outputs.Bucket