AWSTemplateFormatVersion: '2010-09-09'
Description: Builds Roles for Stack

Resources:
  SigningKey:
    Type: AWS::KMS::Key
    Properties:
      Enabled: true
      Description: Key for signing images with cosign
      KeyUsage: SIGN_VERIFY
      KeySpec: ECC_NIST_P521
      MultiRegion: false
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
            - !Sub ${AWS::AccountId}
          Action:
            - kms:*
          Resource: '*'
        - Effect: Deny
          Principal: '*'
          Action:
            - kms:DescribeKey
            - kms:GetPublicKey
            - kms:Sign
            - kms:Verify
          Resource: '*'
          Condition:
            Bool:
              kms:GrantIsForAWSResource: false

  SigningKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${AWS::StackName}-key
      TargetKeyId: !Ref SigningKey

  PipelineKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Used to encrypt and decrypt pipeline data.
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub ${AWS::AccountId}
            Action:
              - kms:*
            Resource: '*'
          - Effect: Deny
            Principal: '*'
            Action:
              - kms:CreateGrant
              - kms:ListGrants
              - kms:RevokeGrant
            Resource: '*'
            Condition:
              Bool:
                kms:GrantIsForAWSResource: false

  PipelineKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${AWS::StackName}
      TargetKeyId: !Ref PipelineKey

Outputs:
  PipelineKey:
    Value: !Ref PipelineKeyAlias
  SigningKey:
    Value: !Ref SigningKeyAlias