AWSTemplateFormatVersion: '2010-09-09'
Description: Builds Bucket for Stack
Parameters:
  ServiceName:
    Type: String
  PipelineKey:
    Type: String

Resources:
  CodePipelineS3Bucket:
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ServiceName}-artifacts
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref PipelineKey
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ExpirationRule
            Status: Enabled
            ExpirationInDays: 7
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True

  CodePipelineS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CodePipelineS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Id: SSEAndSSLPolicy
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub ${AWS::AccountId}
            Action:
              - s3:GetObject
              - s3:GetObjectAcl
              - s3:GetObjectVersion
              - s3:GetObjectVersionAcl
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:PutObjectVersionAcl
            Resource: !Sub arn:${AWS::Partition}:s3:::${CodePipelineS3Bucket}/*
          - Effect: Allow
            Principal:
              AWS:
                - !Sub ${AWS::AccountId}
            Action:
              - s3:ListBucket
            Resource: !Sub arn:${AWS::Partition}:s3:::${CodePipelineS3Bucket}

Outputs:
  Bucket:
    Value: !Ref CodePipelineS3Bucket