name: CVE Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  Anchore_Analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          tags: cluster-sample-app:latest
          push: false
          load: true      
      - uses: anchore/scan-action@v3
        id: scan
        with:
          fail-build: false
          image: "cluster-sample-app:latest"
          acs-report-enable: true
      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
